import React,{useEffect,useState}from"react";
import{createRoot}from"react-dom/client";
import{Activity,AlertTriangle,Brain,Camera,CheckCircle2,ClipboardList,CloudUpload,CreditCard,FileText,Home as HomeIcon,Leaf,Menu,MessageCircle,Phone,Plus,Search,ShieldCheck,ShoppingBag,Stethoscope,UserRound,X}from"lucide-react";
import"./styles.css";import"./firebase";

const animals=[["chicken","🐔","Kuku / Chicken"],["goat","🐐","Goat"],["cow","🐄","Cow / Ng'ombe"],["sheep","🐑","Sheep / Kondoo"],["pig","🐖","Pig / Nguruwe"],["rabbit","🐇","Rabbit / Sungura"],["donkey","🫏","Donkey / Punda"],["horse","🐎","Horse"],["camel","🐪","Camel"],["dog","🐕","Dog / Mbwa"],["cat","🐈","Cat / Paka"],["turkey","🦃","Turkey"],["duck","🦆","Duck / Bata"],["fish","🐟","Fish / Samaki"],["bee","🐝","Bees / Nyuki"],["other","🐾","Other animal"]];
const label=k=>animals.find(a=>a[0]===k)?.[2]||k;
const icon=k=>animals.find(a=>a[0]===k)?.[1]||"🐾";

function App(){
 const[page,setPage]=useState("home"),[open,setOpen]=useState(false);
 const[animalList,setAnimalList]=useState(()=>JSON.parse(localStorage.getItem("sv_animals")||"[]"));
 const[cases,setCases]=useState(()=>JSON.parse(localStorage.getItem("sv_cases")||"[]"));
 useEffect(()=>localStorage.setItem("sv_animals",JSON.stringify(animalList)),[animalList]);
 useEffect(()=>localStorage.setItem("sv_cases",JSON.stringify(cases)),[cases]);
 const nav=[["home","Home",HomeIcon],["farmer","Farmer Portal",UserRound],["ai","AI Vet",Brain],["health","Health Records",Activity],["vet","Veterinarian Portal",Stethoscope],["emergency","Emergency",AlertTriangle],["market","Marketplace",ShoppingBag],["crop","Crop Assistant",Leaf],["admin","Admin Dashboard",ShieldCheck]];
 const go=p=>{setPage(p);setOpen(false)};
 return <div className="app"><header><button className="brand" onClick={()=>go("home")}><span className="logo">🌿</span><span><b>SHAMBA VET</b><small>AI • Veterinary • Farming</small></span></button><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?"open":""}>{nav.map(([id,n,I])=><button className={page===id?"active":""} onClick={()=>go(id)} key={id}><I size={16}/>{n}</button>)}</nav></header><main>
 {page==="home"&&<Home go={go}/>}
 {page==="farmer"&&<Farmer animals={animalList} setAnimals={setAnimalList} go={go}/>}
 {page==="ai"&&<AI cases={cases} setCases={setCases}/>}
 {page==="health"&&<Health animals={animalList} cases={cases}/>}
 {page==="vet"&&<Vet cases={cases} setCases={setCases}/>}
 {page==="emergency"&&<Emergency/>}
 {page==="market"&&<Market/>}
 {page==="crop"&&<Crop/>}
 {page==="admin"&&<Admin animals={animalList} cases={cases}/>}
 </main><footer><b>SHAMBA VET</b><span>AI decision support, not a substitute for a licensed veterinarian.</span><span>Firebase • M-PESA-ready • Vercel-ready</span></footer></div>
}

function Title({I,title,text}){return <div className="title"><div className="ti"><I/></div><div><h1>{title}</h1><p>{text}</p></div></div>}
function Home({go}){return <><section className="hero"><div><span className="pill">FARMER-FIRST PLATFORM</span><h1>Better animal care.<br/><em>Better farming.</em></h1><p>Register animals, keep health records, get AI-assisted veterinary guidance, connect with veterinarians, calculate feed and access farm products.</p><div className="actions"><button className="primary" onClick={()=>go("ai")}><Brain/> Ask AI Vet</button><button onClick={()=>go("farmer")}><UserRound/> Farmer Portal</button><button className="danger" onClick={()=>go("emergency")}><AlertTriangle/> Emergency</button></div></div><div className="heroCard"><b>Shamba Vet</b><strong>9+</strong><span>core modules</span><small>Mobile-first foundation</small></div></section><div className="cards">{[["🤖","AI Veterinary Assistant","Symptoms, safety checks and veterinarian handoff."],["🐄","Animal Records","Registration, photos, treatments and history."],["👨‍⚕️","Veterinarian Portal","Cases, consultations and follow-up."],["🚨","Emergency Help","Fast escalation and contact actions."],["🛒","Marketplace","Feeds, medicines, inputs and shop referrals."],["🌱","Crop Assistant","Crop problems and photo-assessment foundation."]].map(x=><div className="card feature" key={x[1]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></>}

function Farmer({animals:set,setAnimals,go}){const[f,setF]=useState({species:"goat",name:"",age:"",weight:"",tag:""});const add=()=>{if(!f.name)return;setAnimals(a=>[...a,{...f,id:"AN-"+Date.now()}]);setF({species:"goat",name:"",age:"",weight:"",tag:""})};return <><Title I={UserRound} title="Farmer Portal" text="Manage your farm and animal records."/><div className="stats"><Stat n={set.length} t="Animals"/><Stat n="3" t="Free AI checks"/><Stat n="KSh 49" t="Paid check"/><Stat n="24/7" t="Emergency access"/></div><div className="two"><div className="card"><h2>Register animal</h2><select value={f.species} onChange={e=>setF({...f,species:e.target.value})}>{animals.map(a=><option value={a[0]} key={a[0]}>{a[2]}</option>)}</select><input value={f.name} onChange={e=>setF({...f,name:e.target.value})} placeholder="Animal name / ID"/><input value={f.age} onChange={e=>setF({...f,age:e.target.value})} placeholder="Age"/><input value={f.weight} onChange={e=>setF({...f,weight:e.target.value})} placeholder="Weight kg"/><input value={f.tag} onChange={e=>setF({...f,tag:e.target.value})} placeholder="Tag / ear tag"/><button className="primary full" onClick={add}><Plus/> Register animal</button></div><div className="card"><h2>Quick actions</h2><div className="actionGrid"><button onClick={()=>go("ai")}><Brain/> New AI case</button><button onClick={()=>go("health")}><Activity/> Health records</button><button onClick={()=>go("market")}><ShoppingBag/> Shop</button><button onClick={()=>go("emergency")}><AlertTriangle/> Emergency</button></div></div></div><div className="card"><h2>My animals</h2>{set.length?set.map(a=><div className="row" key={a.id}><span className="big">{icon(a.species)}</span><div><b>{a.name}</b><small>{label(a.species)} • {a.weight||"—"} kg • {a.tag||"No tag"}</small></div><span className="status">Active</span></div>):<Empty text="No animals registered yet."/ >}</div></>}

function AI({cases,setCases}){const[a,setA]=useState("goat"),[sym,setSym]=useState(""),[duration,setDuration]=useState(""),[files,setFiles]=useState([]),[r,setR]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const run=async()=>{if(!sym.trim())return;setLoading(true);setError("");setR(null);try{let image=null;if(files[0]&&files[0].type.startsWith("image/")){image={mimeType:files[0].type,data:await toBase64(files[0])}}const response=await fetch("/api/ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({animal:label(a),symptoms:sym,duration,image})});const raw=await response.text();let data={};try{data=raw?JSON.parse(raw):{}}catch{throw new Error("The server returned an invalid response. Check the Vercel deployment logs.");}if(!response.ok)throw new Error(data.error||"AI request failed");setR(data);setCases(c=>[{id:"CASE-"+Date.now(),animal:label(a),symptoms:sym,duration,status:"AI reviewed",media:files.length},...c])}catch(e){setError(e.message)}finally{setLoading(false)}};
 return <><Title I={Brain} title="AI Veterinary Assistant" text="Gemini-powered preliminary veterinary decision support. Upload an animal photo for visual assistance."/><div className="two"><div className="card"><label>Animal</label><select value={a} onChange={e=>setA(e.target.value)}>{animals.map(x=><option value={x[0]} key={x[0]}>{x[2]}</option>)}</select><label>Symptoms</label><textarea value={sym} onChange={e=>setSym(e.target.value)} placeholder="Example: kuku kukohoa, kinyesi white, hailei vizuri..."/><input value={duration} onChange={e=>setDuration(e.target.value)} placeholder="Duration e.g. 2 days"/><label>Animal photo/video</label><div className="upload"><input type="file" multiple accept="image/*,video/*" onChange={e=>setFiles([...e.target.files])}/><CloudUpload/><span>{files.length?files.length+" file(s) selected":"Upload photo/video"}</span></div><button className="primary full" onClick={run} disabled={loading}>{loading?<><Activity/> Asking Gemini...</>:<><Brain/> Analyze with Gemini</>}</button><p className="note"><CreditCard/> 3 free checks, then KSh 49 via M-PESA STK.</p>{error&&<div className="warning emergency"><AlertTriangle/>{error}</div>}</div><div className="card result">{r?<><span className="pill">GEMINI PRELIMINARY GUIDANCE</span><h2>{r.possible}</h2><div className={r.urgency?.startsWith("EMERGENCY")?"warning emergency":"warning"}><AlertTriangle/>{r.urgency}</div><h3>💊 Possible medicine guidance</h3><p>{r.medicine}</p><h3>Safety controls</h3><ul>{(r.questions||[]).map(q=><li key={q}>{q}</li>)}</ul><button className="primary full"><Stethoscope/> Send case to veterinarian</button></>:<Empty text="Gemini assessment will appear here."/ >}</div></div></>}

async function toBase64(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(",")[1]);reader.onerror=reject;reader.readAsDataURL(file)})}

function Health({animals,cases}){return <><Title I={Activity} title="Animal Health Records" text="Foundation for vaccinations, deworming, treatments, breeding and production."/><div className="card">{animals.length?animals.map(a=><div className="record" key={a.id}><div><b>{a.name}</b><small>{label(a.species)} • {a.weight||"—"} kg</small></div><div className="tags"><span>Vaccinations</span><span>Deworming</span><span>Treatments</span><span>Breeding</span></div></div>):<Empty text="Register an animal first."/ >}</div><div className="card"><h2>Veterinary cases</h2>{cases.length?cases.map(c=><div className="row" key={c.id}><div><b>{c.id} • {c.animal}</b><small>{c.symptoms}</small></div><span className="status">{c.status}</span></div>):<Empty text="No cases yet."/ >}</div></>}

function Vet({cases,setCases}){const update=(id,status)=>setCases(c=>c.map(x=>x.id===id?{...x,status}:x));return <><Title I={Stethoscope} title="Veterinarian Portal" text="Review farmer cases, animal history and follow-up."/><div className="stats"><Stat n={cases.length} t="Cases"/><Stat n={cases.filter(c=>c.status==="New").length} t="New"/><Stat n="Verified" t="Account status"/><Stat n="—" t="Appointments"/></div><div className="caseGrid">{cases.map(c=><div className="case card" key={c.id}><span className="pill">{c.status}</span><h3>{c.id} • {c.animal}</h3><p>{c.symptoms}</p><small>Duration: {c.duration||"Not provided"} • Media: {c.media||0}</small><div className="actions"><button onClick={()=>update(c.id,"Accepted")}><CheckCircle2/> Accept</button><button onClick={()=>update(c.id,"Follow-up")}><ClipboardList/> Follow-up</button></div></div>)}</div></>}

function Emergency(){return <><Title I={AlertTriangle} title="Emergency Assistance" text="For serious or life-threatening situations, contact a qualified veterinarian immediately."/><div className="emergencyBox"><AlertTriangle size={58}/><h2>Possible veterinary emergency?</h2><p>Severe breathing difficulty, collapse, uncontrolled bleeding, poisoning, severe bloat and difficult birth require urgent professional help.</p><div className="actions center"><button className="danger"><Phone/> Call veterinarian</button><button className="whatsapp"><MessageCircle/> WhatsApp request</button><button><Search/> Share location</button></div></div></>}

function Market(){return <><Title I={ShoppingBag} title="AgroVet Marketplace" text="Foundation for veterinary products, feeds, seeds, fertilizer and equipment."/><div className="cards">{["Veterinary medicines","Animal feeds","Seeds","Fertilizers","Farm equipment","Agrovet shops"].map(x=><div className="card feature" key={x}><ShoppingBag/><h3>{x}</h3><p>Product catalog, shop referral and order foundation.</p><button className="primary">Browse</button></div>)}</div><div className="card"><h2>Shop commission</h2><p>Clicks, leads and orders can be stored in Firebase and used to calculate a configured referral commission.</p></div></>}

function Crop(){const[p,setP]=useState(""),[r,setR]=useState("");return <><Title I={Leaf} title="Crop Assistant" text="Foundation for crop problem descriptions and photo-assisted agricultural guidance."/><div className="two"><div className="card"><select><option>Maize</option><option>Beans</option><option>Tomato</option><option>Potato</option><option>Other crop</option></select><textarea value={p} onChange={e=>setP(e.target.value)} placeholder="Describe crop symptoms..."/><div className="upload"><input type="file" accept="image/*"/><Camera/><span>Upload crop photo</span></div><button className="primary full" onClick={()=>setR(p?"Possible pest, disease, nutrient or environmental issue. A clear photo and professional confirmation are recommended.":"Describe the problem first.")}><Brain/> Analyze crop</button></div><div className="card result"><Leaf/><h2>{r||"Crop assessment appears here"}</h2></div></div></>}

function Admin({animals,cases}){return <><Title I={ShieldCheck} title="Admin Dashboard" text="Manage users, cases, payments, marketplace and system settings."/><div className="stats"><Stat n={animals.length} t="Animals"/><Stat n={cases.length} t="Cases"/><Stat n="KSh 0" t="Payments"/><Stat n="0" t="Orders"/></div><div className="adminGrid">{["Farmers","Veterinarians","Animal records","Veterinary cases","M-PESA payments","Agrovet shops","Products","Advertisements","Crop cases","System settings"].map(x=><div className="card admin" key={x}><ShieldCheck/><b>{x}</b><span>Manage</span></div>)}</div></>}

function Stat({n,t}){return <div className="stat"><strong>{n}</strong><span>{t}</span></div>}
function Empty({text}){return <div className="empty"><FileText/><p>{text}</p></div>}
createRoot(document.getElementById("root")).render(<App/>);
